#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH


for((i=0;i<1000;i++))
do
	curl  -H "Content-Type:application/json" -X POST --data '{"app_id":"45998196061455024909174081451545","access_token":"cc842832d885c2d083f5e85a1559bf16","time_stamp":"1544775162","device_id":"18110110YT","sign":"c644256cb9cd613ebdb8b41de247e076"}' http://cloudapi.yimii.me/api/Printtask/noPrintOut
done

